import os
import smtplib
from email.message import EmailMessage
from engine import run_engine

def send_email_alert(prediction_data):
    # Retrieve email configuration from environment variables
    # Defaults are provided for testing purposes
    sender_email = os.environ.get("ALERT_SENDER_EMAIL")
    sender_password = os.environ.get("ALERT_SENDER_PASSWORD")
    recipient_list = os.environ.get("ALERT_RECIPIENT_EMAILS", "bacha7@gmail.com").split(",")
    
    if not sender_email or not sender_password:
        print("Error: Email configuration environment variables are missing.")
        print("Please set ALERT_SENDER_EMAIL and ALERT_SENDER_PASSWORD.")
        return False
        
    msg = EmailMessage()
    
    # Format the email content
    subject = f"Daily SPY Trend Alert: {prediction_data['trend']}"
    
    body = f"""
Hello,

Here is your daily SPY trend prediction based on institutional indicators.

------------------------------------------------
SPY PREDICTION SUMMARY
------------------------------------------------
Current Price:    ${float(prediction_data['current_price']):.2f}
Predicted Trend:  {prediction_data['trend']}
Model Confidence: {prediction_data['confidence']:.1f}%
------------------------------------------------

Disclaimer: This is generated by an automated algorithmic model and does not constitute financial advice.

Best regards,
Your Trading Bot
"""
    
    msg.set_content(body)
    msg['Subject'] = subject
    msg['From'] = sender_email
    msg['To'] = ", ".join(recipient_list)
    
    print(f"Sending email alert to {len(recipient_list)} subscriber(s)...")
    
    try:
        # Assuming Gmail SMTP for this example
        # In a real-world scenario, you might use SendGrid or Amazon SES
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        print("Email sent successfully!")
        return True
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False

if __name__ == "__main__":
    print("Running SPY Trend Engine...")
    result = run_engine()
    
    print("Preparing to send email alert...")
    send_email_alert(result)
